### ISSUE TITLE
Long email threads

### ISSUE THREAD

**Issue by petemcfarlane** [phpmentoring/phpmentoring.github.com#26]
Firstly, this project is a great initiative and I have already gained a lot as a mentee and mentor. I have a couple of issues that I don't mind creating a PR for. My main bug-bear is the long email threads. After a couple of messages back and forth I have to do a lot of scrolling to get through to the most recent messages. This is particularly annoying on a mobile phone. A solution to this might be to introduce pagination for long running conversations, or use some accordion/concertina style folding in the UI. Or simply to reverse the order of the messages so the most recent/new is at the top of the page!
Do you have any opinions on how this should be done? I'm willing to help a mentee create a PR to do this.

**Comment by auroraeosrose** [comment]
Could you move this to the webapp repo please? this is the repo for the old static website
