### ISSUE TITLE
Timeout on messaging page

### ISSUE THREAD

**Issue by petemcfarlane** [phpmentoring/phpmentoring.github.com#27]
There seems to be an issue if I don't submit a message in a certain time period. Several times I have been mid writing a message, and when I click Submit I'm redirected to my personal profile page and the message hasn't been sent. Sometimes I'm lucky and can rely on my browser to go back to the page and retrieve the contents, other times I've not immediately noticed and lost all the information I've sent. I haven't looked at the codebase to work out why this happens yet but I'm happy to help a mentee debug and submit a PR to fix this?

**Comment by auroraeosrose** [comment]
Could you move this to the webapp repo please?  This repo is for the old static website
